<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>org.exoplatform.documents-preview</groupId>
    <artifactId>documents-preview</artifactId>
    <version>2.0.x-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <artifactId>documents-preview-services</artifactId>
  <name>eXo Documents preview - Services</name>

  <properties>
    <exo.test.coverage.ratio>0.9</exo.test.coverage.ratio>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.exoplatform.ecms</groupId>
      <artifactId>ecms-core-connector</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.meeds.social</groupId>
      <artifactId>social-component-core</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.exoplatform.documents</groupId>
      <artifactId>documents-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.exoplatform.documents</groupId>
      <artifactId>documents-services</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.artofsolving.jodconverter</groupId>
      <artifactId>jodconverter-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
